export { default as NavBar } from "./minor/NavBar";
export { default as Card } from "./minor/Card";
export { default as FeatureCard } from "./minor/FeatureCard";
export { default as ProfileMenu } from "./minor/ProfileMenu";
export { default as ProfileIcon } from "./minor/Profile-Icon";
export { HeaderProfileIcon } from "./minor/Profile-Icon";
export { AddIcon } from "./minor/Profile-Icon";
export { ShareProfileIcon as ShareProfileIcon } from "./minor/Profile-Icon";
export { default as ProfileImg } from "./minor/Profile_Img";
export { default as Bar } from "./minor/Bar";
export { default as ProfileButton } from "./minor/Profile-Button";
export { ProfileButtonSmall as ProfileButtonSmall } from "./minor/Profile-Button";

export { Stats_Card } from "./minor/Stats_Cards";
export { Empty_Stats } from "./minor/Stats_Cards";
export { HeaderStats } from "./minor/Stats_Cards";

export { default as Hero } from "./major/Hero";
export { default as Sect_1 } from "./major/Sect_1";
export { default as Dev } from "./major/Dev";
export { default as Footer } from "./major/Footer";
export { default as Login } from "./major/Login";
export { default as Signup } from "./major/Signup";
export { default as Forget } from "./major/Forget";
export { default as Feature } from "./major/Feature";
export { default as LinkForm } from "./major/LinkForm";
export { default as External_Links } from "./major/External_Links";

export { Dashboard_Header } from "./major/Header";
export { DashboardProfileButton } from "./minor/Profile-Button";
export { SaveButton } from "./minor/Profile-Button";
export { AddDashboardButton } from "./minor/Profile-Button";
export { Dashboard_Input } from "./minor/Input";
export { EditProfileImg } from "./minor/Profile_Img";
export { HeaderProfileImg } from "./minor/Profile_Img";
export { default as Modal } from "./minor/Modal";
export { default as Edit_Img } from "./major/Edit_Img";
export { default as ButtonForm } from "./major/ButtonForm";
export { default as IconForm } from "./major/IconForm";
export { default as Add_Widget } from "./major/Add_Widget";
export { default as ShareProfile } from "./major/Share";
